### ISSUE TITLE
Report Out

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#123]
MVP:
- Create a report recapping projects implemented throughout the years, energy savings, costs, informational links
- Ability to print to PDF with links to case studies
<img width="590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2g3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c0117d72aec2f81acf8ec0205791c03716fff08/EOG%20Report%20MIN%20%20line.png" alt="EOG Report MIN  line.png" />

Extra:
Enhance the win/lose pages with different animations or spicier content

**Comment by nbintertech** [comment]
Need to change so we're showing emissions differences

**Comment by koay9f** [comment]
This relates to #180's toss back
Either instead of year say "Budget Period" or have it match in game terms of Year 1 & 2 ... 
Everything else is great

<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS9rQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81051876cc234df25107b49c3429a56a4d56122e/image.png" alt="image.png" />
