### ISSUE TITLE
End of Game: Projections on future spending/savings/remaining loans

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#180]
Need to add projected and game total + projected stats to the end of game report

**Comment by koay9f** [comment]
This is part of #206

**Comment by koay9f** [comment]
Love it!
One issue.
I think the report ticks the game over one more year leading to difference between the EoY 9&10 and EoG financing numbers:
EoY 9&10
<img width="1335" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9rQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c79713912dfe2865230f0e54eddb45ac2bbfc9b3/image.png" alt="image.png" />

EoG: 
<img width="1011" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUhrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4641c609b09a788b869ee79a394a2d544459677d/image.png" alt="image.png" />

99% sure the only thing I had "financed" at the end was the small VPPA - $75k/yr; $150k/2-yr period. 

I'm not sure how to resolve this. I think for now, we might just cheat it and title that section 
"As of the end of Years 11 & 12..."  
Otherwise you have to try to specifically remember the end game state I guess (making up words)

**Comment by koay9f** [comment]
Title of page:
"Looking forward - Years 11 & 12" or "Looking forward - Year 11" 
While you haven't started any new projects yet to get to a new goal
* Your company has reduced ...
* You spent (or will spend) {total projected spend $2,178,000} on GHG reduction measures
*  Your cost per kg was {$/kg}
*  After this budget period, you still have {total financing left - $450,000} on financed and renewable projects in the coming years.

**Comment by nbintertech** [comment]
Need to go back and fix this so we've showing numbers from the perspective of year 10 being completed, and still showing financial projections from there

**Comment by nbintertech** [comment]
Ok here's the thing - how the game decides what year we're in is contextually dependant and very confusing. I have notes/issues to fix this for next iteration. I BELIEVE that what we now currently see is correct re: what we talked about in the weekly:

After finishing year 10, in EOG report we are seeing the same game total spend, and game projected spend as we saw in year 10.

**Comment by koay9f** [comment]
Previous comment seems to still be the case.
Purchased large VPPA in years 9&10.  
It's $225000/yr, so $450000/2-yr
At the end of the game, the remaining projected to spend should be 1,800,000 and the total spend should be 3,514,000
<img width="1271" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG9WQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15012b69f3ad9cd5977c4fb7ff75cdd383636ae4/image.png" alt="image.png" />

Interestingly -
if you put it in god mode and choose this at the beginning, the numbers are correct. For all year recaps
<img width="1371" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHdWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0151458f31594ee04464fb56c87947e4e96653e2/image.png" alt="image.png" />

If you skip years 1&2, then purchase large wind in year 3&4...
year 3&4 recap looks good for all year recaps, even the last year

If the only thing you ever purchace is the large VPPA in year 9&10, the numbers look good...
