### ISSUE TITLE
Gauge chart saying change in GHG savings without reflection in table

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#235]
<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeENiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef1b76b9cef669a28207f34c783eefad340c1b42/image.png" alt="image.png" />

Projects:
<img width="582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEdiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99db66e9c72b45d1b4f2070cb5e705c037815ed1/image.png" alt="image.png" />

<img width="375" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFNiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e83150de87702dbc9a666db91778ef27016788de/image.png" alt="image.png" />

**Comment by koay9f** [comment]
It could be that the table isn't using the new emission factor

The table should show 3 decimals for the electricity emission factor

**Comment by rhernandez-intertech** [comment]
Found a bug in the code that pertains to the calculation of emissions from electricity, so that is getting fixed and changing the table to display the emissions rate to 3 decimal places. Also, the inconsistency in result calculations is due to how many significant figures are being use. For example, 234,600 MMBT * 53.1 kg/mmbtu * 1 tonne/1000kg does equal 12,457 tonne, however the code is using 53.06 as the natural gas emissions rate, so running that equation again with 53.06 instead of 53.1 results in 12,447 tonne, so changing the table to display the emissions rate to 3 decimal places will fix this inconsistency.
